# docker-compose.yml
version: "12.5"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER= prometheusdb
      - POSTGRES_PASSWORD= prometheusdb
      - POSTGRES_DB= prometheusdb
    ports:
      - "5532:5432"
