# docker-compose.yml
version: "12.5"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER= postgresdb
      - POSTGRES_PASSWORD= postgresdb
      - POSTGRES_DB= postgresdb
      - POSTGRES_host=postgresdb.cf3lrno7mqrm.us-east-2.rds.amazonaws.com
    ports:
      - "5532:5432"
