# docker-compose.yml
version: "12.5"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= postgres
      - POSTGRES_host= postgres.cf3lrno7mqrm.us-east-2.rds.amazonaws.com
    ports:
      - "5532:5432"
